### ISSUE TITLE
events on SnacBar done

### ISSUE THREAD

**Issue by jeanPokou** [polonel/SnackBar#1]
Hello nice snackbar , but do you have any events attached to the snackbar ,so we can dettach it from the DOM when its done

**Comment by polonel** [comment]
Currently there is only the `onActionClick` event that fires when the action button is clicked. 
By default this event fades out the Snackbar. 
The Snackbar is removed from the DOM when a new Snackbar is created.

**Comment by jeanPokou** [comment]
I have used **onActionClick** it's pretty useful, but I want to detached it from the DOM because the z-index is 9999, so everything underneath is not clickable

**Comment by polonel** [comment]
Fixed the issue where the Snackbar was not being removed from DOM.

**Comment by blindfish3** [comment]
Whilst you may have solved the OP's rendering issue; an onClose callback could have other useful applications and make your snackbar more flexible.  For example I'd like to create a queue of notifications.  An onClose event would allow me to trigger the display of the next queued notification.  Or is there another way to implement that?

**Comment by polonel** [comment]
@blindfish3: I have added onClosed event in 0.1.10
