### ISSUE TITLE
Responsive?

### ISSUE THREAD

**Issue by Aditya94A** [polonel/SnackBar#10]
This doesn't really look right on mobile, how about following material design principles kinda like [this library](https://github.com/dmuy/Material-Toast)?

**Comment by polonel** [comment]
Do you mind showing me what it renders as on your device. This is what I show..

![img_4889](https://user-images.githubusercontent.com/626303/32916163-37dd8d06-cae9-11e7-847a-224903fdce49.jpg)

**Comment by Aditya94A** [comment]
Ahh, so the bottom left one looks normal (as in your screenshot), right and center ones look like this for me: 

<img width="211" alt="screenshot 2017-11-17 09 39 03" src="https://user-images.githubusercontent.com/13274079/32929050-5a5c227e-cb7b-11e7-8490-207c166ccd7c.png">

**Comment by polonel** [comment]
Thanks for pointing that out. I’m getting a fix together.

**Comment by aexvir** [comment]
@polonel Please take a look at the PR I sent. The issue seems to be solved.
