### ISSUE TITLE
How add customClass ?

### ISSUE THREAD

**Issue by calonzolg** [polonel/SnackBar#11]
hello Chris, 
i'm using the key: customClass for put font into bold, but only affect the dismiss message

![image](https://user-images.githubusercontent.com/19369562/34674869-23c2d05a-f44d-11e7-95e8-596be577a5ab.png)

![image](https://user-images.githubusercontent.com/19369562/34674903-490953de-f44d-11e7-9009-114513e6dc32.png)

want the font bold that is on the black square,

have a nice day, 

PS: my english is not good sorry :s

**Comment by polonel** [comment]
The customClass is targeted for the snacker container. Which means you can use the customClass on the container to target the child element you wish you change. You may have to append the css `!important` tag.

So in your case you could target the `p` element with...
``` css
.myCustomClass p {
   font-weight: bold !important;
}
```
