### ISSUE TITLE
Unlimited time

### ISSUE THREAD

**Issue by isatria** [polonel/SnackBar#14]
Does it support unlimited time appearing until the action button is pressed?

**Comment by aexvir** [comment]
@isatria Yes, setting the duration to 0 or null results in a Snackbar visible until dismissed. The documentation should be updated to reflect this behavior, and maybe even having a property other than duration.

**Comment by aexvir** [comment]
@polonel If you set up a repo for the demo page I can submit a PR to fix this issue. And I'd like to know your opinion in using a different property to make it unlimited. Also we could accept the string 'unlimited' as a valid duration value to have this behavior.

**Comment by isatria** [comment]
Thank you for responding

Actually I have not implemented this on my project, I just want to know ahead of time if this is capable of handling for needs with `appearing` cases with unlimited time

but thanks for the offer.

**Comment by aexvir** [comment]
@isatria But still, the documentation doesn't reflect this behaviour and it should be updated. If @polonel agrees and provides a public repo for the demo page I can submit a PR addressing this issue. If not maybe he can change it so as everyone can use that property.

**Comment by polonel** [comment]
@isatria @aexvir I'll get a repo up to the demo site first chance I get. Thank you for your contributions.

**Comment by aexvir** [comment]
@polonel Please tag me when you have set up the repo. Thanks!

**Comment by polonel** [comment]
@aexvir Demo repo [github.com/polonel/SnackbarDemo](https://github.com/polonel/SnackbarDemo)
@aexvir https://github.com/polonel/SnackbarDemo/invitations
