### ISSUE TITLE
Feature request: add option to show() to specify insertion point

### ISSUE THREAD

**Issue by blindfish3** [polonel/SnackBar#15]
Seeing as you're obviously receptive to suggestions (thanks for implementing my suggestion in #1) I have another one :)

It would be nice to have an option in show() to specify the element into which the snackbar gets inserted (e.g. so it can be positioned above a footer).  Seems simple enough to implement - e.g. something like this appears to work fine for me:

snackbar.js
``` 
   // document.body.appendChild(Snackbar.snackbar);
    var target = document.querySelector(options.target) || document.querySelector('body');
    target.appendChild(Snackbar.snackbar);
```

...with the default of options.target set to 'body': the fallback is just there in case someone screws up the selector and it can't be resolved.  It's then possible to override the CSS locally to position in relation to the parent container.

**Comment by aexvir** [comment]
@blindfish3 Can you elaborate more on this request? Right now the snackbar is using position fixed with a quite high z-index. Does your footer have a greater z-index than the snackbar?

In my opinion inserting the snackbar into whatever element doesn't make many sense if your issue is simply that you have stuff over it. Simply increase the z-index of the snackbar-container class or try to have a lower z-index on the element that is overlapping.

**Comment by blindfish3** [comment]
Not a z-index issue - I meant above the footer on the y-axis: the snackbar gets a little lost when over a busy footer; so I want it to be sticky and remain fixed to the top of the footer when this is on screen.  Must admit I haven't looked in detail at how I'd implement this...  I probably have to use some JS anyway so I'm sure I can figure out a workaround ;)

**Comment by polonel** [comment]
@blindfish3 From my understanding of what you're trying to accomplish would be positioning the snackbar above the footer if you have a tall (height) footer. If that is the case that would go against the MD design principles when showing the snackbar on the bottom of the page. This is why the snackbar has multiple display positions. (Top-Left, Top-Right) You can easily change the display position based on how much of the footer is shown on screen.

I'm going to close this issue as there're already ways around this issue built into the component.
