### ISSUE TITLE
Improvement: Use npm extend module

### ISSUE THREAD

**Issue by blindfish3** [polonel/SnackBar#16]
Looks like [extend](https://www.npmjs.com/package/extend) is equivalent to the Extend function you have hard-coded in snackbar.js - you could just import that instead; but maybe you're deliberately avoiding external module dependencies?

**Comment by aexvir** [comment]
What's the point on having a dependency only for that matter? I recommend you to read [this](https://medium.com/@caspervonb/the-internet-is-at-the-mercy-of-a-handful-of-people-73fac4bc5068) article about npm dependencies. 😄
