### ISSUE TITLE
Website example wrong

### ISSUE THREAD

**Issue by emmetarries** [polonel/SnackBar#17]
The home page of your website: [https://www.polonel.com/snackbar/](https://www.polonel.com/snackbar/) has the following code for the Download yourself option:
`<link ref="stylesheet" type="text/css" href="dist/snackbar.min.css" /> <script src="dist/snackbar.min.js"></script> `
It should be: (notice **rel** instead of **ref**)
`<link rel="stylesheet" type="text/css" href="dist/snackbar.min.css" /> <script src="dist/snackbar.min.js"></script> `

It screwed me up for longer than I would like to admit, please fix it.

**Comment by aexvir** [comment]
Thanks for pointing that out. I commited a fix right now 😅
