### ISSUE TITLE
Duration isn't working

### ISSUE THREAD

**Issue by IvaWonderbush** [polonel/SnackBar#2]
It seems like the duration isn't working. Here is a little snippit:

```
var SnackBar = require('node-snackbar');

$(document).ready(function () {
    var liveNotice = $('.live-notice').text();

    SnackBar.show({
        text: liveNotice,
        pos: 'bottom-center',
        showActionButton: false,
        duration: 10000
    });
});
```

I've tried setting the duration to well over 10 seconds yet the default of 5 is still being used. On ^0.1.0.

**Comment by que01** [comment]
I meet this issue too. I download the files and modify by myself, but I hope you could fix this bug,tks!

I find the error has fixed in source code, bug in the npm,it's still not work,please update it.

**Comment by polonel** [comment]
NPM has been updated.
