### ISSUE TITLE
ReferenceError: actionTextAria is not defined

### ISSUE THREAD

**Issue by IS-Kuan** [polonel/SnackBar#20]
Got a `ReferenceError: actionTextAria is not defined` with `node-snackbar@0.1.12`
https://github.com/polonel/SnackBar/commit/5f9a70ccb4eb0e10c20dcaf2ca8607a868bbb8cb#r31146058

**Comment by petertenhoor** [comment]
+1, same issue here. Reverting to an older version for now.

**Comment by polonel** [comment]
The update has been pushed to npm. Typo in PR.
