### ISSUE TITLE
`index.d.ts` is not found if installing via npm.

### ISSUE THREAD

**Issue by kuanyui** [polonel/SnackBar#24]
The file `index.d.ts` is  missing in `node_modules/node-snackbar/` if install `node-snackbar@0.1.14` via npm.

I've never publish any package onto **npm** so I don't know whether there is any other procedure is required to fix this.

[The document of TypeScript about this](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) seems to talk nothing about this, but I found the `package.js` of [noty](https://github.com/needim/noty/blob/master/package.json), which is written in native JS, [contains following lines](https://github.com/needim/noty/blob/master/package.json#L20-L24):
```
  "files": [
    "lib",
    "src",
    "index.d.ts"
  ],
```
Though I don't sure if this is the point.

**Comment by polonel** [comment]
Should be fixed. I pushed 0.1.15 to npm.

Update and give it a go.

**Comment by kuanyui** [comment]
Awesome! It works now :D
